source 'http://rubygems.org'

gem 'rails', '2.3.8'
gem 'mongrel'
gem 'mysql', '2.8.1'
gem 'paperclip', '2.3.8'
gem 'fastercsv', '1.5.3'
gem 'mongo', '1.1.5'
gem 'bson_ext', '1.1.5'
gem 'curb'
gem 'ruby-imagespec', '0.2.0'
gem 'thin'
gem 'rake', '0.8.7'
gem 'dalli', '1.0.1'
gem 'sass'
gem 'aws-s3', '0.6.2'

group :test do
  gem 'rspec-rails', '1.3.4'
  gem 'factory_girl', '1.3.2'
  gem 'cucumber-rails', '0.3.2'
  gem 'database_cleaner', '0.6.3'
  gem 'selenium-client', '1.2.18'
  gem 'webrat', '0.7.3'
  gem 'mocha', '0.9.9'
  gem 'ruby-debug','0.10.3'
end

