#!/usr/bin/env ruby

require 'optparse'

options = {}
parser = OptionParser.new do |opts|
  opts.banner = "Usage: script/workflows/clearspring-collect-cleanup [options]"
  
  opts.separator ''
  opts.separator 'Action options: (by default, clean up downloaded files over 4 days old and temporary files over 6 hours old)'
  
  opts.on('-d', '--downloaded', 'Clean up downloaded files only') do
    options[:downloaded] = true
  end
  opts.on('-D', '--downloaded-age AGE', 'Specify the age of downloaded files to clean up') do |age|
    options[:downloaded_age] = age
  end
  opts.on('-t', '--temporary', 'Clean up temporary files only') do
    options[:temporary] = true
  end
  opts.on('-T', '--temporary-age AGE', 'Specify the age of temporary files to clean up') do |age|
    options[:temporary_age] = age
  end
  
  opts.separator ''
  opts.separator 'Configuration options:'
  
  opts.on('-c', '--config-file PATH', 'Specify configuration file path (by default, config/workflows/clearspring.yml is used)') do |path|
    options[:config_path] = path
  end
  
  opts.separator ''
  opts.separator 'Debugging options:'
  
  opts.on('--[no-]debug', 'Enable debugging output') do |value|
    options[:debug] = value
  end
  
  opts.separator ''
  opts.separator 'Informational options:'
  
  opts.on('-h', '--help', 'Display this help text') do
    puts opts
    exit
  end
end.parse!

require File.join(File.dirname(__FILE__), '../../config/boot')
require File.join(File.dirname(__FILE__), '../../config/environment')

# 4 days for downloaded files
# 6 hours for temporary files
default_age = {:downloaded => 4 * 86400, :temporary => 6 * 3600}

unless options[:downloaded] || options[:temporary]
  options[:downloaded] = true
  options[:temporary] = true
end

%w(downloaded temporary).each do |which|
  key = "#{which}_age".to_sym
  if value = options[key]
    begin
      options[key] = TimeDistanceParser.parse(value)
    rescue ArgumentError => e
      $stderr.puts "Invalid age value: #{value}: #{e.message}"
      exit(3)
    end
  else
    options[key] = default_age[which.to_sym]
  end
end

require 'find'
require 'fileutils'

def cleanup(dir, age, options={})
  threshold = Time.now - age
  Find.find(dir) do |path|
    if %w(.svn .git).include?(File.basename(path))
      Find.prune
    end
    
    next unless FileTest.file?(path)
    
    mtime = File.stat(path).mtime
    if mtime < threshold
      if options[:debug]
        debug_print("Remove #{path}")
      end
      
      FileUtils.rm(path)
    end
  end
end

def debug_print(msg)
  Workflow.default_logger.debug('clearspring-collect-cleanup') { msg }
end

settings = ClearspringExtractWorkflow::Configuration.new(options)
params = settings.merge_user_options(options)

if options[:downloaded]
  cleanup(params[:download_root_dir], options[:downloaded_age], params)
end

if options[:temporary]
  cleanup(params[:gzip_root_dir], options[:temporary_age], params)
end
