require 'spec_helper'

describe LandingPagesController do
  # This test case was generated by rspec.
  it "should use LandingPagesController" do
    controller.should be_an_instance_of(LandingPagesController)
  end

  describe "GET 'metrics'" do
    # Requesting the metrics form should render the form.
    it "should be successful" do
      get 'metrics'
      response.should be_success
      response.should render_template('metrics')
    end
  end

  describe "GET 'report'" do
    # Basic functionality check - requesting a report with some
    # sensible parameters should not produce errors.
    it "should be successful" do
      # report fails when invoked without parameters, should it redirect
      # to metrics in such case instead?
      get 'report',
        :start_year => 2010, :start_month => 1, :start_day => 1,
        :end_year => 2011, :end_month => 1, :end_day => 1,
        :frequency => 'hour', :metrics => ['impression_count'],
        :format => 'html'
      # we get redirected to facts controller with adjusted parameters
      response.should be_redirect
=begin does not seem to work
      response.should redirect_to(
        :controller => 'facts', :action => 'index', :format => 'html',
        :start_time => '2010-01-01', :end_time => '2011-01-01',
        :tz_offset => 0,
        :frequency => 'hour', :metrics => 'impression_count',
        :dimensions => ''
      )
=end
    end
  end
end
