namespace :db do
  desc "Create seed file from audiences in beacon.\nIMPORTANT: THIS IS A ONE "+
    "TIME TASK TO BE PERFORMED DURING THE MIGRATION OF XGCC TO PRODUCTION USE"
  task :audience_seed_file_from_beacon => :environment do 
    seeds = []
    for audience in Beacon.new.audiences
        seeds << "{ :description => \"#{audience.name}\", "+
        ":audience_code => \"#{
          Audience.find_by_beacon_id(audience.beacon_id).blank? ?
            Audience.generate_audience_code :
            Audience.find_by_beacon_id(audience.beacon_id).audience_code
        }\", "+
        ":beacon_id => #{audience["id"]} }"
    end
    seed_string = "# ============================================================"+
      "==========\n"+
      "# THIS IS A POINT-IN-TIME SEED FILE GENERATED BY THE"+
      "# audience_seed_file_from_beacon\n"+
      "# RAKE TASK CONTAINING ALL BEACON AUDIENCES AT THE TIME THE TASK WAS RUN\n"+
      "# ======================================================================\n"+
      "Audience.seed_many(:beacon_id, [\n#{seeds.join(",\n")}\n])"
    
    seed_file = File.join(RAILS_ROOT, "db", "fixtures", "audiences_from_beacon.rb")
    File.open(seed_file, 'w') do |f| 
        f.write seed_string
    end
  end

  desc "Create seed file from audiences in beacon and use it to seed "+
    "the XGCC audiences table."
  task :seed_beacon_audiences => [ :environment, :audience_seed_file_from_beacon ] do
    ENV["SEED"] = "audiences_from_beacon"
    Rake::Task["db:seed_fu"].execute
  end

  desc "Set to null all beacon ids referring to non-existant beacon audiences"
  task :remove_zombie_beacon_ids => [ :environment ] do
    beacon_ids = {}
    Beacon.new.audiences.collect { |a| beacon_ids[a.id] = true }
    for audience in Audience.all
      unless beacon_ids[audience.beacon_id]
        audience.update_attributes(:beacon_id => nil)
      end
    end
  end
end
